services:
  frontend:
    image: banking-frontend
    pull_policy: never
    container_name: banking-frontend
    build:
      context: ./Frontend/banking-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend-network

  backend:
    image: banking-backend
    pull_policy: never
    container_name: banking-backend
    build:
      context: ./Backend/banking-server
      dockerfile: ./src/main/docker/Dockerfile.jvm
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - frontend-network
      - backend-network

  database:
    image: banking-postgres-database
    pull_policy: never
    container_name: banking-postgres-database
    build:
      context: ./Database
      dockerfile: Dockerfile
    volumes:
      - banking-postgres-data:/var/lib/postgresql/data
    env_file:
      - ./Database/database.env
    networks:
      - backend-network

volumes:
  banking-postgres-data:

networks:
  frontend-network:
  backend-network: